# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class CallRoutingRecordedFile(BaseModel):
    """
    Recorded file.
    """  # noqa: E501

    id: Optional[StrictStr] = Field(default=None, description="File ID.")
    name: Optional[StrictStr] = Field(default=None, description="File name.")
    file_format: Optional[StrictStr] = Field(
        default=None, description="File format.", alias="fileFormat"
    )
    size: Optional[StrictInt] = Field(default=None, description="File size in bytes.")
    start_time: Optional[datetime] = Field(
        default=None,
        description="Date and time when the recording started.",
        alias="startTime",
    )
    end_time: Optional[datetime] = Field(
        default=None,
        description="Date and time when the recording ended.",
        alias="endTime",
    )
    creation_time: Optional[datetime] = Field(
        default=None, description="File creation time.", alias="creationTime"
    )
    duration: Optional[StrictInt] = Field(
        default=None, description="File duration in seconds."
    )
    location: Optional[StrictStr] = Field(
        default=None, description="Location of recording file after processing."
    )
    custom_data: Optional[Dict[str, StrictStr]] = Field(
        default=None, description="Client-defined data.", alias="customData"
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "fileFormat",
        "size",
        "startTime",
        "endTime",
        "creationTime",
        "duration",
        "location",
        "customData",
    ]

    @field_validator("file_format")
    def file_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["MP3", "WAV", "MP4"]):
            raise ValueError("must be one of enum values ('MP3', 'WAV', 'MP4')")
        return value

    @field_validator("location")
    def location_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["UPLOADING", "UPLOADED", "HOSTED"]):
            raise ValueError(
                "must be one of enum values ('UPLOADING', 'UPLOADED', 'HOSTED')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CallRoutingRecordedFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CallRoutingRecordedFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "fileFormat": obj.get("fileFormat"),
                "size": obj.get("size"),
                "startTime": obj.get("startTime"),
                "endTime": obj.get("endTime"),
                "creationTime": obj.get("creationTime"),
                "duration": obj.get("duration"),
                "location": obj.get("location"),
                "customData": obj.get("customData"),
            }
        )
        return _obj
