# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CallsWaitForEom(str, Enum):
    """
    Indicates whether end of the message detection is enabled for the call. `ALWAYS` specifies that after detection of `MACHINE` the script will always wait for the end of the message before executing actions defined in `onMachineDetected`. `NEVER` specifies that after detection of `MACHINE` actions defined in `onMachineDetected` will be executed immediately. `ON_DETECTING` specifies that end of the message will be respected as long as actions in `onDetecting` are in progress, once these actions finish the script jumps to `onMachineDetected` section immediately.
    """

    """
    allowed enum values
    """
    ALWAYS = "ALWAYS"
    NEVER = "NEVER"
    ON_DETECTING = "ON_DETECTING"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CallsWaitForEom from a JSON string"""
        return cls(json.loads(json_str))
