# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EmailValidationReason(str, Enum):
    """
    Reason is provided when validMailbox status is unknown. 1. INBOX_FULL - The user quota exceeded / The user inbox is full / The user doesn't accept any more requests. 2. UNEXPECTED_FAILURE - The mail Server returned a temporary error. 3. THROTTLED - The mail server is not allowing us momentarily because of too many requests. 4. TIMED_OUT - The mail Server took a longer time to respond / there was a delay in the network. 5. TEMP_REJECTION - Mail server temporarily rejected. 6. UNABLE_TO_CONNECT - Unable to connect to the Mail Server.
    """

    """
    allowed enum values
    """
    TIMED_OUT = "TIMED_OUT"
    TEMP_REJECTION = "TEMP_REJECTION"
    THROTTLED = "THROTTLED"
    INBOX_FULL = "INBOX_FULL"
    UNABLE_TO_CONNECT = "UNABLE_TO_CONNECT"
    UNEXPECTED_FAILURE = "UNEXPECTED_FAILURE"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EmailValidationReason from a JSON string"""
        return cls(json.loads(json_str))
