# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HmacAlgorithm(str, Enum):
    """
    HMAC algorithm.
    """

    """
    allowed enum values
    """
    HMAC_MD5 = "HMAC_MD5"
    HMAC_SHA_1 = "HMAC_SHA_1"
    HMAC_SHA_224 = "HMAC_SHA_224"
    HMAC_SHA_256 = "HMAC_SHA_256"
    HMAC_SHA_384 = "HMAC_SHA_384"
    HMAC_SHA_512 = "HMAC_SHA_512"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HmacAlgorithm from a JSON string"""
        return cls(json.loads(json_str))
