# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from infobip_api_client.models.messages_api_message_button import (
    MessagesApiMessageButton,
)
from infobip_api_client.models.messages_api_message_button_type import (
    MessagesApiMessageButtonType,
)
from infobip_api_client.models.messages_api_open_url_button_open_in import (
    MessagesApiOpenUrlButtonOpenIn,
)
from typing import Optional, Set
from typing_extensions import Self


class MessagesApiMessageOpenUrlButton(MessagesApiMessageButton):
    """
    MessagesApiMessageOpenUrlButton
    """  # noqa: E501

    text: StrictStr = Field(description="Text to be displayed on the button.")
    url: StrictStr = Field(description="URL to be opened when clicked on the button.")
    postback_data: Optional[StrictStr] = Field(
        default=None,
        description="Custom data that will be sent to you when the user replies to the message.",
        alias="postbackData",
    )
    open_in: Optional[MessagesApiOpenUrlButtonOpenIn] = Field(
        default=None, alias="openIn"
    )
    type: MessagesApiMessageButtonType = "OPEN_URL"
    __properties: ClassVar[List[str]] = [
        "type",
        "text",
        "url",
        "postbackData",
        "openIn",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessagesApiMessageOpenUrlButton from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessagesApiMessageOpenUrlButton from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "type": obj.get("type"),
                "text": obj.get("text"),
                "url": obj.get("url"),
                "postbackData": obj.get("postbackData"),
                "openIn": obj.get("openIn"),
            }
        )
        return _obj
