# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from infobip_api_client.models.messages_api_message_payment_beneficiary import (
    MessagesApiMessagePaymentBeneficiary,
)
from infobip_api_client.models.messages_api_message_payment_configuration import (
    MessagesApiMessagePaymentConfiguration,
)
from infobip_api_client.models.messages_api_message_payment_configuration_type import (
    MessagesApiMessagePaymentConfigurationType,
)
from typing import Optional, Set
from typing_extensions import Self


class MessagesApiMessageUpiPgRazorpayPaymentConfiguration(
    MessagesApiMessagePaymentConfiguration
):
    """
    MessagesApiMessageUpiPgRazorpayPaymentConfiguration
    """  # noqa: E501

    id: Optional[StrictStr] = Field(
        default=None,
        description="Unique identifier of the payment. It can only contain English letters, numbers, underscores, dashes, or dots, and should not exceed 35 characters",
    )
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=60)]] = (
        Field(
            default=None,
            description="Name of the WhatsApp payment configuration to be used for this order.",
        )
    )
    beneficiary: Optional[MessagesApiMessagePaymentBeneficiary] = None
    callback_data: Optional[Dict[str, StrictStr]] = Field(
        default=None,
        description="Object with key value pairs containing custom parameters corresponding to the transaction.",
        alias="callbackData",
    )
    type: MessagesApiMessagePaymentConfigurationType = "PG_RAZORPAY"
    __properties: ClassVar[List[str]] = [
        "type",
        "id",
        "name",
        "beneficiary",
        "callbackData",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessagesApiMessageUpiPgRazorpayPaymentConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of beneficiary
        if self.beneficiary:
            _dict["beneficiary"] = self.beneficiary.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessagesApiMessageUpiPgRazorpayPaymentConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "type": obj.get("type"),
                "id": obj.get("id"),
                "name": obj.get("name"),
                "beneficiary": (
                    MessagesApiMessagePaymentBeneficiary.from_dict(obj["beneficiary"])
                    if obj.get("beneficiary") is not None
                    else None
                ),
                "callbackData": obj.get("callbackData"),
            }
        )
        return _obj
