# coding: utf-8

"""
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

The version of the OpenAPI document: 1.0.0
Contact: support@infobip.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ViberOtpTemplateLanguage(str, Enum):
    """
    Language to be used for the template. If not set, the device language will be used.
    """

    """
    allowed enum values
    """
    ENGLISH = "ENGLISH"
    ARABIC = "ARABIC"
    BULGARIAN = "BULGARIAN"
    CROATIAN = "CROATIAN"
    CZECH = "CZECH"
    DANISH = "DANISH"
    GERMAN = "GERMAN"
    GREEK = "GREEK"
    SPANISH = "SPANISH"
    FINNISH = "FINNISH"
    FRENCH = "FRENCH"
    HEBREW = "HEBREW"
    BURMESE = "BURMESE"
    HUNGARIAN = "HUNGARIAN"
    INDONESIAN = "INDONESIAN"
    ITALIAN = "ITALIAN"
    JAPANESE = "JAPANESE"
    NORWEGIAN = "NORWEGIAN"
    DUTCH = "DUTCH"
    POLISH = "POLISH"
    PORTUGUESE_PORTUGAL = "PORTUGUESE_PORTUGAL"
    PORTUGUESE_BRAZIL = "PORTUGUESE_BRAZIL"
    ROMANIAN = "ROMANIAN"
    RUSSIAN = "RUSSIAN"
    SLOVAK = "SLOVAK"
    SERBIAN = "SERBIAN"
    SWEDISH = "SWEDISH"
    THAI = "THAI"
    TURKISH = "TURKISH"
    UKRAINIAN = "UKRAINIAN"
    VIETNAMESE = "VIETNAMESE"
    PERSIAN = "PERSIAN"
    BELARUSIAN = "BELARUSIAN"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ViberOtpTemplateLanguage from a JSON string"""
        return cls(json.loads(json_str))
